# Generated by Django 3.2.25 on 2026-01-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Phone', 'Phone'), ('Document', 'Document'), ('Bag', 'Bag'), ('Others', 'Others')], max_length=50)),
                ('description', models.TextField()),
                ('location_found', models.CharField(max_length=100)),
                ('date_found', models.DateField()),
                ('contact', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Phone', 'Phone'), ('Document', 'Document'), ('Bag', 'Bag'), ('Others', 'Others')], max_length=50)),
                ('description', models.TextField()),
                ('location_lost', models.CharField(max_length=100)),
                ('date_lost', models.DateField()),
                ('contact', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('recovered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
